name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:


jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

# re-enable this when the socket.io issue has been resolved.
# `bahmutov/npm-install` does not work with yarn resolutions here, as yarn is not used due to https://github.com/bahmutov/npm-install/issues/95
#  test-no-lock:
#    name: Floating Dependencies
#    runs-on: ubuntu-latest
#    needs:
#      - test
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Setup node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: 12
#      - name: Install dependencies
#        uses: bahmutov/npm-install@v1
#        with:
#          useLockFile: false
#      - name: Test
#        run: yarn test:ember

  test-try:
    name: Additional Tests
    runs-on: ubuntu-latest
    needs:
      - test
    strategy:
      matrix:
        scenario:
          - ember-release
          - ember-beta
          - ember-canary
          - embroider-safe
          - embroider-optimized
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn ember try:one ${{ matrix.scenario }}
        working-directory: packages/test-app